// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Board = require("./Board.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Button = require("./Button.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* status */0];
              return React.createElement("div", {
                          className: "app"
                        }, React.createElement("div", {
                              className: "game"
                            }, match ? ReasonReact.element(undefined, undefined, Button.make("Start Game!", (function (param) {
                                          return Curry._1(self[/* send */3], /* Start */0);
                                        }), /* array */[])) : ReasonReact.element(undefined, undefined, Board.make(self[/* state */1][/* activeMole */1], /* array */[]))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* status : NotStarted */1,
                      /* activeMole */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[
                            /* status */state[/* status */0],
                            /* activeMole */action[0]
                          ]]);
              } else {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* record */[
                            /* status : Started */0,
                            /* activeMole */state[/* activeMole */1]
                          ],
                          (function (self) {
                              setInterval((function (param) {
                                      var randomInt = Js_math.random_int(0, 9);
                                      return Curry._1(self[/* send */3], /* ChangeActiveMole */[randomInt]);
                                    }), 1000);
                              return /* () */0;
                            })
                        ]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
